email: EMAIL

packages:
  - sudo
  - unattended-upgrades
  - tmux
  - htop
  - python3

ssh_config_path: /etc/ssh/sshd_config
sshd_name: ssh

lan_subnet: 192.168.0.0/24
lan_base_ip: "{{ lan_subnet | regex_replace('.0/[0-9]{2}', '') }}"
server_ip: "{{ lan_base_ip }}.26"

ssh_port: 22
ssh_password_authentication: "no"
ssh_permit_root_login: "no"
ssh_usedns: "no"
ssh_permit_empty_password: "no"
ssh_challenge_response_auth: "no"
ssh_gss_api_authentication: "no"
ssh_x11_forwarding: "no"
# Autoupdate mail settings
autoupdate_reboot: "true"
autoupdate_reboot_time: "03:00"
autoupdate_mail_to: "{{ email }}"
autoupdate_mail_on_error: true
autoupdate_blacklist: []

fail2ban_custom_configuration_template: "jail.local.j2"